# Your workflow name.
name: Deploy to render.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to render. # Your custom step name
        uses: johnbeynon/render-deploy-action@v0.0.8 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your render app.

          # render service id which can be found in the service's url
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          
          # render API key associated with provided user's email.
          # Api Key is available under your render account settings.
          api-key: ${{ secrets.RENDER_API_KEY }}
          

          wait-for-success: true

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.render.com/articles/process-model
          process_type: web
          
   
          
### ⬆ IMPORTANT PART ⬆ ###